### PR TITLE
pip requirements allow numpy>=1.7

### PR DESCRIPTION
**Pull request by breznak**
as a step to upgrading to numpy 1.9
part of #1516

### CODE REVIEW

**Comment by scottpurdy** [comment]
This change actually does upgrade numpy to the latest version and will mean that the version used is whatever the latest version is. This deviates from our current policy of fixing versions to ensure that we get deterministic builds.

@rhyolight my suggestion is that we explicitly change the version to the latest and close #1516.

**Comment by rhyolight** [comment]
I thought that this change would NOT install a newer version of numpy if version 1.7 or higher already existed on the user system? So it only affects new installations of numpy with nupic.

**Comment by scottpurdy** [comment]
That's true but it still means we have no idea what version they will have. And Travis, etc will be using whatever the latest is.

**Comment by rhyolight** [comment]
Ok, but I didn't think upgrading to 1.9.1 was a simple task, that's why #1516 is open. I would love to do exactly what you said:

> we explicitly change the version to the latest and close #1516.

So we agree there. But I'm not sure that simply updating the requirements string is sufficient to close #1516.

**Pull request merged**
