### PR TITLE
Anomaly strict

### PR DESCRIPTION
**Pull request by breznak**
Work towards #1300 
Currently implements that also "predicted but not found" patterns contribute to anomaly score. 

TODO:
- [ ] 1/ change Anomaly class to take array of columns' permanences as input
- [ ] 1.2/ Then anomaly class can be a stateful machine and can take only 1 argument (actual permances) and and keep track of the "prevPredictedColumns" itself.
- [ ] 2/ revert `computeRawAnomalyScore` back and add a new `MODE_` for the new anomaly, vs. having the one and only anomaly computation method?
- [ ] 3/ use only the true predicted columns (permanence>=threshold) as "predicted" columns.

Please let me know what you think about the TODO items. 
:1234:

### CODE REVIEW

**Comment by rhyolight** [comment]
GitHub won't let me re-open this issue (WHY??), but it should be opened again. I'm complaining to them now.

**Comment by breznak** [comment]
@rhyolight - this is a PR, not an issue, #1300 is the issue. 
Btw, the reopen button says 'there is already a pull request from breznak:anomaly_strict to numenta:master' -- I think I force-pushed the branch and it got messed up somehow, anyway, we can let this one rot here for ethernity :devilgrin:

**Comment by rhyolight** [comment]
Yeah I figured that out. I didn't get enough sleep last night (currently on a flight from NYC -> SF).

**Comment by cogmission** [comment]
Don't flush when you're overhead of Chicago please!  :)

**Pull request closed without merging**
